services:
  - type: web
    name: historieta-andrea
    env: static
    staticPublishPath: .
    buildCommand: ""
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
